version: '3.4'

services:
  db:
    image: mysql:5.6.41
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-large-prefix=true --innodb-file-format=Barracuda
    environment:
      MYSQL_ROOT_PASSWORD: pass0000
      MYSQL_DATABASE: test_development
      MYSQL_USER: root
      MYSQL_PASSWORD: pass0000
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3308:3306"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/system
    ports:
      - "3003:3000"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db

  terraform: &terraform
    image: hashicorp/terraform:0.12.18
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    env_file:
      - .env

  tflint:
    <<: *terraform
    image: wata727/tflint
