version: '3.4'

services:
  terraform: &terraform
    image: hashicorp/terraform:0.12.18
    volumes:
      - ./terraform:/terraform
    working_dir: /terraform
    env_file:
      - .env

  tflint:
    <<: *terraform
    image: wata727/tflint
