AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'ssm-notification

  Sample SAM Template for ssm-notification

  '
Globals:
  Function:
    Timeout: 3
Resources:
  SSMNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://system-maneger-test/6563a47c07d0f167636cf43a478e4b8a
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ENDPOINT: https://hooks.slack.com/services/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
      Events:
        SSMEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              Fn::Sub: "{\n  \"source\": [\n    \"aws.ssm\"\n  ],\n  \"detail-type\"\
                : [\n    \"AWS API Call via CloudTrail\"\n  ],\n  \"detail\": {\n\
                \    \"eventSource\": [\n      \"ssm.amazonaws.com\"\n    ],\n   \
                \ \"eventName\": [\n      \"StartSession\",\n      \"TerminateSession\"\
                \n    ]\n  }\n}\n"
