AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ssm-notification

  Sample SAM Template for ssm-notification

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SSMNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ENDPOINT: https://hooks.slack.com/services/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
      Events:
        SSMEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              !Sub |
              {
                "source": [
                  "aws.ssm"
                ],
                "detail-type": [
                  "AWS API Call via CloudTrail"
                ],
                "detail": {
                  "eventSource": [
                    "ssm.amazonaws.com"
                  ],
                  "eventName": [
                    "StartSession",
                    "TerminateSession"
                  ]
                }
              }
